POST http://localhost:8011/users HTTP/1.1
content-type: application/json

{
    "Id": "{{$randomInt 1 10000}}",
    "name": "Greg"
}

### 

GET http://localhost:8011/users HTTP/1.1



### 
    
GET http://localhost:8011/users/23044444 HTTP/1.1



### 
GET http://localhost:8011/hc HTTP/1.1