POST http://localhost:8011/users HTTP/1.1
content-type: application/json

{
    "Id": "1",
    "name": "Greg"
}

### 

GET http://localhost:8011/users HTTP/1.1



### 
    
GET http://localhost:8011/users/1 HTTP/1.1



### 
GET http://localhost:8011/hc HTTP/1.1