POST http://localhost:8011/users HTTP/1.1
content-type: application/json

{
    "Id": "1",
    "name": "bob"
}

### 

GET http://localhost:8011/users HTTP/1.1



### 
    
GET http://localhost:8011/users/1 HTTP/1.1